### ISSUE TITLE
Pen tool not working as espected

### ISSUE THREAD

**Issue by ttrova** [Ekhynox/Dessine-moi-un-mouton#1]
When clicking : the pen tool is doesn't do the right thing
objective -> single click = dot
right now -> single click = line from here to here (so nothing visible)

idea to resolve : change the line theme from "sharp ending" to "round ending"
idea to resolve : detect small line and print dot instead of line

**Comment by D32mond** [comment]
Solved
Thanks, to supporting.

-Kévin
